In [ ]:
# DATA CLEANING
# Checking for missing values
import pandas as pd
import numpy as np
# Create a dataframe
data={
    'First Score':[100,90,np.nan,9],
    'Second Score':[30,45,60,np.nan],
    'Third Score':[np.nan,45,90,45]
}
df=pd.DataFrame(data)
print(df)
print('----------------------------------------------------------------')
# Checking for Missing Values
mv=df.isnull()
print(mv)
print('----------------------------------------------------------------')
# Using the second method
mv1=df.isna()
print(mv1)
print('----------------------------------------------------------------')
# Checking for the Not null values
mv2=df.notnull()
print(mv2)

   First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0          45.0         45.0
2          NaN          60.0         90.0
3          9.0           NaN         45.0
----------------------------------------------------------------
   First Score  Second Score  Third Score
0        False         False         True
1        False         False        False
2         True         False        False
3        False          True        False
----------------------------------------------------------------
   First Score  Second Score  Third Score
0        False         False         True
1        False         False        False
2         True         False        False
3        False          True        False
----------------------------------------------------------------
   First Score  Second Score  Third Score
0         True          True        False
1         True          True         True
2        False          True         True
3         True         False         True

In [16]:
# Filling up Missing values
# Method 1 using fillna() Function
import pandas as pd
import numpy as np
# Create a dataframe
data={
    'First Score':[100,90,np.nan,9],
    'Second Score':[30,45,60,np.nan],
    'Third Score':[np.nan,45,90,45]
}
df=pd.DataFrame(data)
print(df)
# Filling missing values
mv=df.fillna(0)
print('--------------------------------------------------------------------------------')
print(mv)
# Using Replace() function
print('--------------------------------------------------------------------------------')
mv1=df.replace(to_replace=np.nan, value=130)
print(mv1)

# Using interpolate() Function
data1={
    'A':[21,23,54,None],
    'B':[12,None,76,98],
    'C':[None,65,23,90],
    'D':[12,43,56,89]
}
df1=pd.DataFrame(data1)
print('--------------------------------------------------------------------------------')
print(df1)
# Filling the missing values using interpolate() function
mv3=df1.interpolate(method='linear',limit_direction='forward')
print('--------------------------------------------------------------------------------')
print(mv3)
# Dropping null values
print('--------------------------------------------------------------------------------')
mv4=df1.dropna()
print(mv4)
# Without returning a new dataframe
mv5=df1.dropna(inplace=True)
print('--------------------------------------------------------------------------------')
print(mv5)

   First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0          45.0         45.0
2          NaN          60.0         90.0
3          9.0           NaN         45.0
--------------------------------------------------------------------------------
   First Score  Second Score  Third Score
0        100.0          30.0          0.0
1         90.0          45.0         45.0
2          0.0          60.0         90.0
3          9.0           0.0         45.0
--------------------------------------------------------------------------------
   First Score  Second Score  Third Score
0        100.0          30.0        130.0
1         90.0          45.0         45.0
2        130.0          60.0         90.0
3          9.0         130.0         45.0
--------------------------------------------------------------------------------
      A     B     C   D
0  21.0  12.0   NaN  12
1  23.0   NaN  65.0  43
2  54.0  76.0  23.0  56
3   NaN  98.0  90.0  89
--------------------------------------------------------------------------------
      A     B     C   D
0  21.0  12.0   NaN  12
1  23.0  44.0  65.0  43
2  54.0  76.0  23.0  56
3  54.0  98.0  90.0  89
--------------------------------------------------------------------------------
      A     B     C   D
2  54.0  76.0  23.0  56
--------------------------------------------------------------------------------
None

In [21]:
import pandas as pd
import numpy as np
# Create a dataframe
data={
    'First Score':[100,90,np.nan,9],
    'Second Score':[30,45,60,np.nan],
    'Third Score':[np.nan,45,90,45]
}
df=pd.DataFrame(data)
# Creating a csv file
df.to_csv('file7.csv', index=False)
# Filling missing values using mean
df1=pd.read_csv('file7.csv')
x=df1['First Score'].mean()
df1.fillna({'First Score': x},
inplace=True )

# Filling missing value 2
y=df1['Second Score'].mean()
df1.fillna( {
    'Second Score': y
    },
           inplace=True
           )

# Filling missing value 3
z=df1['Third Score'].mean()
df1.fillna(
    {
        'Third Score':z
    },
    inplace=True
)

   First Score  Second Score  Third Score
0   100.000000          30.0         60.0
1    90.000000          45.0         45.0
2    66.333333          60.0         90.0
3     9.000000          45.0         45.0

In [28]:
import pandas as pd
# Reading a dataframe
df=pd.read_csv('file7.csv')
print(df)
print('--------------------------------------------------------------------------')
# Checking for missing values
mv=df.isnull()
print(mv)
# Replacing missing values using fillna
print('--------------------------------------------------------------------------')
mv1=df.fillna(4.5)
print(mv1)
print('--------------------------------------------------------------------------')
# Replacing missing values using the missing values using mean
mv2=df['First Score'].mean()
df.fillna({'First Score': mv2
           },
          inplace=True)
# Replacing missing values in the second column using median
mv3=df['Second Score'].median()
df.fillna({'Second Score':mv3},
          inplace=True)
# Replacing missing value using the mode
mv4=df['Third Score'].mode()
df.fillna({'Third Score': mv4},
          inplace=True)

   First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0          45.0         45.0
2          NaN          60.0         90.0
3          9.0           NaN         45.0
--------------------------------------------------------------------------
   First Score  Second Score  Third Score
0        False         False         True
1        False         False        False
2         True         False        False
3        False          True        False
--------------------------------------------------------------------------
   First Score  Second Score  Third Score
0        100.0          30.0          4.5
1         90.0          45.0         45.0
2          4.5          60.0         90.0
3          9.0           4.5         45.0
--------------------------------------------------------------------------

   First Score  Second Score  Third Score
0   100.000000          30.0         45.0
1    90.000000          45.0         45.0
2    66.333333          60.0         90.0
3     9.000000          45.0         45.0