In [2]:
import pandas as pd
#  Create a dataframe
students={
    'Name':['John', 'Mary','Peter','Grace','David','Sarah','James','Linda'],
    'Math':[85,90,65,95,72,88,55,80],
    'English':[78,88,70,92,75,90,60,85],
    'Science':[92,85,60,96,70,84,58,82],
    'Attendance':[95,98,80,99,85,97,75,90]
}
df=pd.DataFrame(students)
df.to_csv('Results.csv')
df

    Name  Math  English  Science  Attendance
0   John    85       78       92          95
1   Mary    90       88       85          98
2  Peter    65       70       60          80
3  Grace    95       92       96          99
4  David    72       75       70          85
5  Sarah    88       90       84          97
6  James    55       60       58          75
7  Linda    80       85       82          90

In [35]:
import pandas as pd
# Load dataset into pandas
df=pd.read_csv('Results.csv')
df

# DATA CLEANING
# Exploring the first five columns
print('================================================================')
ED=df.head()
print(ED)
# Exploring the last five columns
print('================================================================')
ED1=df.tail()
print(ED1)
# Exploring dataset information
print('================================================================')
ED2=df.info()
print(ED2)
# Exploring dataset description
print('================================================================')
ED3=df.describe()
print(ED3)
# Identifying dataset shape
print('================================================================')
ED4=df.shape 
print(ED4)
# Trimming the dataset
print('================================================================')
df=df.drop(columns='Unnamed: 0')
df

# Checking the number of students in the dataset
print('================================================================')
ED5=df['Name'].count()
print(f'Number of students in the dataset: {ED5}')

# Calculating the average math score
print('================================================================')
ED6=df['Math'].mean()
print(f'Average Math Score: {ED6}')

# Finding out who scored the highest in science
print('================================================================')
ED7=df['Science'].max()
ED8=df[df['Science']==ED7]
print(f'Highest Score in Science: {ED7}')
print(f'Student Who score the Highest in Science: \n {ED8}')

# Students with attendance below 85%
print('================================================================')
ED9=df[df['Attendance']<85]
print(f'Student with Attendance below 85%: \n {ED9}')

# =============== FEATURE ENGINEERING ==================================
# Adding Total Marks column
print('================================================================')
df['Total Marks']=df['Math']+df['English']+df['Science']
df
# Adding and calculating the average column
df['Average']=df['Total Marks']/3
df
df['Average']=df['Average'].round(2)
df
# Sorting students from the largest
df=df.sort_values(by=['Total Marks'], ascending=False)
df

# Grading the students
# Creating a Grade function
def grade(score):
    if score>=80:
        return 'A'
    elif score>=70:
        return 'B'
    elif score>=60:
        return 'C'
    elif score>=50:
        return 'D'
    else:
        return 'F'
    
# Applying the funtion to the dataset
df['Grade']=df['Average'].apply(grade)
df

================================================================
   Unnamed: 0   Name  Math  English  Science  Attendance
0           0   John    85       78       92          95
1           1   Mary    90       88       85          98
2           2  Peter    65       70       60          80
3           3  Grace    95       92       96          99
4           4  David    72       75       70          85
================================================================
   Unnamed: 0   Name  Math  English  Science  Attendance
3           3  Grace    95       92       96          99
4           4  David    72       75       70          85
5           5  Sarah    88       90       84          97
6           6  James    55       60       58          75
7           7  Linda    80       85       82          90
================================================================
<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  8 non-null      int64
 1   Name        8 non-null      str
 2   Math        8 non-null      int64
 3   English     8 non-null      int64
 4   Science     8 non-null      int64
 5   Attendance  8 non-null      int64
dtypes: int64(5), str(1)
memory usage: 516.0 bytes
None
================================================================
       Unnamed: 0       Math    English    Science  Attendance
count     8.00000   8.000000   8.000000   8.000000    8.000000
mean      3.50000  78.750000  79.750000  78.375000   89.875000
std       2.44949  13.708704  11.093756  14.181855    9.014869
min       0.00000  55.000000  60.000000  58.000000   75.000000
25%       1.75000  70.250000  73.750000  67.500000   83.750000
50%       3.50000  82.500000  81.500000  83.000000   92.500000
75%       5.25000  88.500000  88.500000  86.750000   97.250000
max       7.00000  95.000000  92.000000  96.000000   99.000000
================================================================
(8, 6)
================================================================
================================================================
Number of students in the dataset: 8
================================================================
Average Math Score: 78.75
================================================================
Highest Score in Science: 96
Student Who score the Highest in Science:
     Name  Math  English  Science  Attendance
3  Grace    95       92       96          99
================================================================
Student with Attendance below 85%:
     Name  Math  English  Science  Attendance
2  Peter    65       70       60          80
6  James    55       60       58          75
================================================================

    Name  Math  English  Science  Attendance  Total Marks  Average Grade
3  Grace    95       92       96          99          283    94.33     A
1   Mary    90       88       85          98          263    87.67     A
5  Sarah    88       90       84          97          262    87.33     A
0   John    85       78       92          95          255    85.00     A
7  Linda    80       85       82          90          247    82.33     A
4  David    72       75       70          85          217    72.33     B
2  Peter    65       70       60          80          195    65.00     C
6  James    55       60       58          75          173    57.67     D